# NOTACION YAML PARA LA CREACION DE ATRIBUTOS PARA VARIOS ASPECTOS
# CONEXION A LA BBDD
# COMUNICACION CON HIBERNATE
# PUERTO DE SALIDA DE LA APLICACION
# Y OTROS ASPECTOS
spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://192.168.83.128:5432/prueba-db
    username: sqluser
    password: D3v310p34202x-GD
  jpa:
    show-sql: true
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    open-in-view: false
    generate-ddl: true
    hibernate:
      ddl-auto: none
server:
  port: 9090
#SWAGGER
springdoc:
  packages-to-scan: 'com.blumbit.web.api.appgradle.controller'
logging:
  pattern:
    console: "%d{dd-MM-yyyy HH:mm:ss.SSS} [%t] %-5level %logger{36} - %msg%n"
    file: "%d{dd-MM-yyyy HH:mm:ss.SSS} %p %c{1.} [%t] %m%n"
  level:
    org.springframework.web: ERROR
    com.blumbit.web.api.appgradle: DEBUG
    org.hibernate: ERROR
  file:
    name: app-personas.log
